---
- name: Remove DBServer Packages 
  hosts: "{{ target_host_name }}*"
  become: yes
  become_method: sudo  

  tasks:
  - name: remove mysql server, mysql-python
    yum:
      name:
        - mariadb-server
        - MySQL-python
      state: absent

  - name: disable mysql port 3306
    firewalld:
      port: "3306/tcp"
      state: disabled
      permanent: true
    notify: restart firewall

  handlers:
  - name: restart firewall 
    service:
      name: firewalld
      state: restarted
...
