---
- name: Test HTTP Output from Desktop using Firefox
  hosts: "{{ target_host_name }}*" 
  gather_facts: yes
  become: yes
  become_method: sudo  

  tasks:
  - name: "calling Firefox. Please see desktop terminal"
    command: "firefox --new-tab http://{{ ansible_default_ipv4.address }} --display=:0"
    delegate_to: desktop
...
