---
- name: Download the previous copy of website source codes
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: clear websource directory
    file: 
      path: "/tmp/websource"
      state: absent  
  - name: get the latest webpage source from git
    git:
      repo: "https://github.com/felizkk/php-website-demo.git"
      dest: "/tmp/websource"

- name: Rollback Previous Website to Webservers
  hosts: "{{ target_host_name }}*"
  gather_facts: no
  become: yes
  become_method: sudo
    
  vars:
    - dbserver_ip_address: "10.68.158.101"

  tasks:
  - name: clear html directory
    file: 
      path: /var/www/html
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  # Important Note: to enable Tower to access /tmp, the Job Isolation feature must be disabled
  # On Tower v3.3.0 : Settings - Jobs - Job Isolation - Off
  - name: rollback index php file
    template:
      src: "/tmp/websource/website-{{ rollback_version }}/jinja/index.php.j2"
      dest: "/var/www/html/index.php"

  - name: copy the rest of html files
    copy:
      src: "/tmp/websource/website-{{ rollback_version }}/static/"
      dest: /var/www/html/
...